# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Permalinks
permalink:        pretty

# Setup
title:            'The Links Report'
description:      'Handcrafted artisan links by <a href="https://github.com/daniellittledev/">Daniel Little</a>'
url:              https://daniellittledev.github.io/links/
future:           true
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Daniel Little'
  url:            https://github.com/daniellittledev

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-algolia

# Custom vars
sidebar_home_link:  false

google_analytics: G-41PXCZ3F8L

feed:
  path: atom.xml

algolia:
  application_id: BSLW1CYPLE
  index_name: jekyll
  search_only_api_key: 4358c506a01c33061176537a4a026b2b
  nodes_to_index: li

social:
  description: 'Handcrafted artisan links by Daniel Little'
  domain: 'https://daniellittledev.github.io/links/'
